### ISSUE TITLE
click on the page button then go to home page.

### ISSUE THREAD

**Issue by FrostyLeaf** [vayser/react-js-pagination#7]
Hi, there! I found a problem in some situations. Each page button has a 'href' attr with value '#', when I click on it,  instead of next page in current route, the location change to home page. But in some other websites, it works well.
I don't know how it happened for now, but I think you may change the href as 'javascript:void(0);', this can work in any situation.

**Comment by vayser** [comment]
i am not sure that problem is with react-js-pagination module, module prevent default behaviour when link clicked, so i think problem is in you onChange handler or in your router.

technique that you suggested is a bad practice: 
http://stackoverflow.com/questions/2479557/why-is-it-bad-practice-to-use-links-with-the-javascript-protocol
